package Calculator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class FrameCal2 extends javax.swing.JFrame {

    /**
     * Creates new form FrameCal2
     */
    public FrameCal2() {
        initComponents();
        
        BigText.setEnabled(false);
        SmallText.setEnabled(false);
        
        Label1.setVisible(false);
        Label2.setVisible(false);
        Label3.setVisible(false);
        
        setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Multiply = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Equals = new javax.swing.JButton();
        C = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        Num7 = new javax.swing.JButton();
        Dot = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        SmallText = new javax.swing.JTextField();
        Num9 = new javax.swing.JButton();
        BigText = new javax.swing.JTextField();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Percentage = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Num1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Multiply.setText("X");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Num3.setText("3");
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });

        Divide.setText("/");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        Equals.setText("=");
        Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsActionPerformed(evt);
            }
        });

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        Num0.setText("0");
        Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num0ActionPerformed(evt);
            }
        });

        Num7.setText("7");
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });

        Dot.setText(".");
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });

        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });

        SmallText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallTextActionPerformed(evt);
            }
        });
        SmallText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SmallTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SmallTextKeyReleased(evt);
            }
        });

        Num9.setText("9");
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });

        BigText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Num4.setText("4");
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });

        Num5.setText("5");
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });

        Percentage.setText("%");
        Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageActionPerformed(evt);
            }
        });

        Num6.setText("6");
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });

        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Num1.setText("1");
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });

        Delete.setText("<---");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Num2.setText("2");
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1)
                .addGap(94, 94, 94)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(Label3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(BigText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SmallText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(Label2)
                    .addComponent(Label3))
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(SmallText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(BigText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ClassCal2 sample = new ClassCal2();

String name,name1,name2,name3,name4,newname,newname2,newname3,newname4;
double num,num2;
    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"x");
        Label2.setText("-");

    }//GEN-LAST:event_MultiplyActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"3");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"3");
        }else{
            Label3.setText(Label3.getText()+"3");
        }

    }//GEN-LAST:event_Num3ActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
        if (!BigText.getText().isEmpty()) {
            SmallText.setText(BigText.getText());
            Label1.setText(BigText.getText());
            Label2.setText("");
            Label3.setText("");
            BigText.setText("");
        }

        SmallText.setText(SmallText.getText()+"/");
        Label2.setText("/");
    }//GEN-LAST:event_DivideActionPerformed

    private void EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsActionPerformed
        // TODO add your handling code here:
        if (SmallText.getText().isEmpty()){
            BigText.setText("0");
        }else if (Label2.getText().equals("+")) {
            num = Double.parseDouble(Label1.getText());
            num2 = Double.parseDouble(Label3.getText());
            sample.Add(num, num2);
            if (sample.getTotal()%1==0) {
                BigText.setText((int)sample.getTotal()+"");
            }else{
                BigText.setText(sample.getTotal()+"");
            }

        }else if (Label2.getText().equals("-")) {
            num = Double.parseDouble(Label1.getText());
            num2 = Double.parseDouble(Label3.getText());
            sample.Subtract(num, num2);
            if (sample.getTotal()%1==0) {
                BigText.setText((int)sample.getTotal()+"");
            }else{
                BigText.setText(sample.getTotal()+"");
            }
        }else if (Label2.getText().equals("x")) {
            num = Double.parseDouble(Label1.getText());
            num2 = Double.parseDouble(Label3.getText());
            sample.Multiply(num, num2);
            if (sample.getTotal()%1==0) {
                BigText.setText((int)sample.getTotal()+"");
            }else{
                BigText.setText(sample.getTotal()+"");
            }
        }else if (Label2.getText().equals("/")) {
            num = Double.parseDouble(Label1.getText());
            num2 = Double.parseDouble(Label3.getText());
            sample.Divide(num, num2);
            if (sample.getTotal()%1==0) {
                BigText.setText((int)sample.getTotal()+"");
            }else{
                BigText.setText(sample.getTotal()+"");
            }
        }else if (Label2.getText().equals("%")){
            double num = Double.parseDouble(Label1.getText());
            sample.Remainder(num);
            if (sample.getTotal()%1==0) {
                BigText.setText((int)sample.getTotal()+"");
            }else{
                BigText.setText(sample.getTotal()+"");
            }
        }

    }//GEN-LAST:event_EqualsActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        SmallText.setText("");
        BigText.setText("");
        Label1.setText("");
        Label2.setText("");
        Label3.setText("");
        sample.setTotal(0);
    }//GEN-LAST:event_CActionPerformed

    private void Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num0ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"0");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"0");
        }else{
            Label3.setText(Label3.getText()+"0");
        }

    }//GEN-LAST:event_Num0ActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"7");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"7");
        }else{
            Label3.setText(Label3.getText()+"7");
        }

    }//GEN-LAST:event_Num7ActionPerformed

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotActionPerformed
        // TODO add your handling code here:

        SmallText.setText(SmallText.getText()+".");
        if (!Label1.getText().isEmpty()) {
            Label3.setText(Label3.getText()+".");
        }else if (!Label2.getText().isEmpty()){
            Label3.setText(Label3.getText()+".");
        }else{
            Label1.setText(Label1.getText()+".");
        }
    }//GEN-LAST:event_DotActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"8");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"8");
        }else{
            Label3.setText(Label3.getText()+"8");
        }

    }//GEN-LAST:event_Num8ActionPerformed

    private void SmallTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallTextActionPerformed
        // TODO add your handling code here:sadad12121121
    }//GEN-LAST:event_SmallTextActionPerformed

    private void SmallTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SmallTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallTextKeyPressed

    private void SmallTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SmallTextKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallTextKeyReleased

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"9");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"9");
        }else{
            Label3.setText(Label3.getText()+"9");
        }

    }//GEN-LAST:event_Num9ActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"4");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"4");
        }else{
            Label3.setText(Label3.getText()+"4");
        }

    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"5");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"5");
        }else{
            Label3.setText(Label3.getText()+"5");
        }

    }//GEN-LAST:event_Num5ActionPerformed

    private void PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageActionPerformed
        // TODO add your handling code here:
        if (!BigText.getText().isEmpty()) {
            SmallText.setText(BigText.getText());
            Label1.setText(BigText.getText());
            Label2.setText("");
            Label3.setText("");
            BigText.setText("");
        }

        SmallText.setText(SmallText.getText()+"%");
        Label2.setText("%");
    }//GEN-LAST:event_PercentageActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"6");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"6");
        }else{
            Label3.setText(Label3.getText()+"6");
        }
    }//GEN-LAST:event_Num6ActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
        if (!BigText.getText().isEmpty()) {
            SmallText.setText(BigText.getText());
            Label1.setText(BigText.getText());
            Label2.setText("");
            Label3.setText("");
            BigText.setText("");
        }

        SmallText.setText(SmallText.getText()+"+");
        Label2.setText("+");
    }//GEN-LAST:event_PlusActionPerformed

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"1");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"1");
        }else{
            Label3.setText(Label3.getText()+"1");
        }

    }//GEN-LAST:event_Num1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try{
            name = SmallText.getText();
            newname = name.substring(0,name.length()-1);
            SmallText.setText(newname);

            if (Label2.getText().isEmpty()) {
                name2 = Label1.getText();
                newname2 = name2.substring(0, name2.length()-1);
                Label1.setText(newname2);
            }else if (Label3.getText().isEmpty()){
                name4 = Label2.getText();
                newname4 = name4.substring(0,name4.length()-1);
                Label2.setText(newname4);
            }else if (!Label2.getText().isEmpty()) {
                name3 = Label3.getText();
                newname3 = name3.substring(0, name3.length()-1);
                Label3.setText(newname3);
            }
        }catch(Exception e){
            sample.setTotal(0);
            BigText.setText("");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        // TODO add your handling code here:
        if (!BigText.getText().isEmpty()) {
            SmallText.setText(BigText.getText());
            Label1.setText(BigText.getText());
            Label2.setText("");
            Label3.setText("");
            BigText.setText("");
        }

        if (!BigText.getText().isEmpty()) {
            SmallText.setText(BigText.getText());
            Label1.setText(BigText.getText());
            Label2.setText("");
            Label3.setText("");
            BigText.setText("");
        }

        SmallText.setText(SmallText.getText()+"-");
        Label2.setText("-");

    }//GEN-LAST:event_MinusActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        // TODO add your handling code here:
        SmallText.setText(SmallText.getText()+"2");

        if (Label2.getText().isEmpty()) {
            Label1.setText(Label1.getText()+"2");
        }else{
            Label3.setText(Label3.getText()+"2");
        }
    }//GEN-LAST:event_Num2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BigText;
    private javax.swing.JButton C;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Equals;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton Percentage;
    private javax.swing.JButton Plus;
    private javax.swing.JTextField SmallText;
    // End of variables declaration//GEN-END:variables
}
